Core/urls.py
from .views import IndexView,  BlogView, BlogDetailView, SaveContactView, FeedbackView, AlumniView, RegistrationView, EmailTemplatesView
from django.conf.urls import url

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^savecontact$', SaveContactView.as_view(), name='save_contact'),
    url(r'^register', RegistrationView.as_view(), name='registration'),
    url(r'^blogs', BlogView.as_view(), name='blog'),
    url(r'^blogs/(?P<pk>\d+)/detail', BlogDetailView.as_view(), name='blog_detail'),
    url(r'^feedback', FeedbackView.as_view(), name='feedback'),
    # url(r'^alumni_registration$', AlumniRegistrationView.as_view(), name='alumni_registration'),
    url(r'^alumni/(?P<batch>[0-9]+)/(?P<slug>[a-zA-Z-]+)/$', AlumniView.as_view(), name='alumni_detail'),
    url(r'^kk/sigret/', EmailTemplatesView.as_view(), name='sigret'),

]

Core/models.py
from __future__ import unicode_literals

import os
import uuid
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.db import models
from ckeditor.fields import RichTextField

from ckeditor_uploader.fields import RichTextUploadingField

#from ckeditor_uploader.fields import RichTextUploadingField

from django.core.validators import RegexValidator,FileExtensionValidator
from django.template.defaultfilters import slugify
from django.utils.translation import gettext_lazy as _
# DO NOT DELETE THIS FUNCTION
# If you think that this function is outright useless because it is never called,
# stop right there. You delete this and all the migrations will FAIL!


def upload_location(instance, filename):
    return '%s/%s' % (instance.id, filename)


def members_upload_location(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('uploads/members', filename)


def projects_upload_location(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('uploads/projects', filename)


def events_upload_location(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('uploads/events', filename)


def event_validator(value):
    if value is True and Event.objects.filter(active=True).count() >= 1:
        raise ValidationError(
            'More than one events cannot be active at a given time'
        )


class Event(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False, validators=[event_validator, ])
    pic_path = models.FileField(upload_to=events_upload_location, null=True,
                                default=None)

    def __str__(self):
        return self.name


class ContactUs(models.Model):
    name = models.CharField(max_length=255)
    contact = models.BigIntegerField()
    email = models.EmailField(max_length=50)
    subject = models.CharField(max_length=255)
    message = models.CharField(max_length=5000)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'contact us'


class Designation(models.Model):
    name = models.CharField(max_length=225, unique=True, null=False,
                            blank=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Designations"


class Technology(models.Model):
    name = models.CharField(max_length=225, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Technologies"


class Member(models.Model):
    name = models.CharField(max_length=225, null=False, blank=False)
    designation = models.ForeignKey(to=Designation, null=True,on_delete= models.CASCADE)
    technology = models.ManyToManyField(to=Technology)
    presently_at = models.CharField(max_length=225, null=False, blank=True)
    is_alumni = models.BooleanField(default=False)
    batch = models.IntegerField(null=False)
    pic_path = models.FileField(upload_to=members_upload_location, null=True,
                                default=None)
    facebook = models.CharField(max_length=225, null=True, default=None)
    github = models.CharField(max_length=225, null=True, default=None)
    linkedin = models.CharField(max_length=225, null=True, default=None)
 
    testimonial = models.TextField(max_length=500, null=True, blank=True, default=None)
    message = models.TextField(max_length=500, null=True, default='LOVE-PEACE-CODE')
    email = models.EmailField(max_length=225, null=True, blank=True, default=None)
    phone = models.CharField(max_length=10, null=True, blank=True, default=None)
    slug = models.SlugField(max_length=255, null=True, blank=True)

    def save(self, *args, **kwargs):
            self.slug = slugify(self.name)
            super().save(*args, **kwargs)

    def __str__(self):
        return self.name + " | " + str(
            self.batch) + " | " + self.designation.name

    class Meta:
        verbose_name_plural = "Members"
        ordering = ['batch']


class Project(models.Model):
    name = models.CharField(max_length=225, null=False, blank=False)
    description = models.CharField(max_length=225, null=False, blank=False)
    completion_year = models.IntegerField(null=True, default=None)
    image_path = models.FileField(upload_to=projects_upload_location, null=True,
                                  default=None)

    def __str__(self):
        return self.name + str(self.completion_year)

    class Meta:
        verbose_name_plural = "Projects"


class Branch(models.Model):
    name = models.CharField(max_length=10, null=False)
    active = models.BooleanField(default=True)
    code = models.IntegerField(null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Branches'


class Year(models.Model):
    class year_choices(models.IntegerChoices):
        First = 1 , _('1st year')
        Second = 2, _('2nd year')
        Third = 3, _('3rd year')
        Forth = 4,_('4th year')
    value = models.IntegerField(choices=year_choices.choices)
    active = models.BooleanField(default=True)

    def __str__(self):
        return str(self.get_value_display())

    class Meta:
        ordering = ['value',]


def student_number_validator(value):
    if Registration.objects.filter(student_number=value,
                                   event=Event.objects.filter(
                                           active=True).first()).exists():
        raise ValidationError(
            'Student number already registered!'
        )

class Registration(models.Model):
    # experience_choices = [
    #     ('no','No Experience'),
    #     ('beginner',"Beginner"),
    #     ('intermediate','Intermediate'),
    #     ('expert','Expert')
    # ]

    name = models.CharField(max_length=100, null=False)
    college_email = models.EmailField(unique=True)
    # roll_no = models.CharField(max_length=13,default="123")
    #changing just for first year registration
    roll_no = models.CharField(max_length=13, null=True)
    student_number = models.CharField(max_length=10, unique=True)
    phone = models.CharField(max_length=10, null=False)
    branch = models.ForeignKey('Branch',on_delete=models.CASCADE)
    gender = models.ForeignKey('Gender',default=1,related_name='registrations',on_delete=models.CASCADE)
    # year = models.ForeignKey('Year',default=2,on_delete=models.CASCADE)
    # domain = models.ForeignKey('Domain',default=1,related_name='registrations',on_delete=models.CASCADE)
     # Default Year is 1 for SI Workshop
    year = models.ForeignKey('Year',default=1,on_delete=models.CASCADE)
    # Registration for workshop doesn't require Domain so Null=True
    domain = models.ForeignKey('Domain',related_name='registrations',on_delete=models.CASCADE, null=True)
    skills = models.CharField(max_length=250,default="HTML",help_text='Skills like HTML, CSS, Java...')
    hacker_rank_username = models.CharField(max_length=250,null=True,blank=True,help_text='Your HackerRank username. Please create an account on HackerRank.')
    timestamp = models.DateTimeField(auto_now_add=True)
    event = models.ForeignKey('Event',on_delete=models.CASCADE)
    your_work = models.TextField(blank=True,null=True,help_text='Links to your work or coding profiles.')
    is_hosteler = models.BooleanField(default=False)
    mail_sent_status = models.BooleanField(default=False)
    is_paid = models.BooleanField(default=False)
    # whatsapp = models.CharField(max_length=10, default="9999999999", null=False)
    # experience = models.CharField(choices=experience_choices,max_length=20,null=False,blank=False)
    # account_handles = models.CharField(max_length=500, blank=True)
    # about_yourself = models.TextField(max_length=500, blank=True)
    # why_attend = models.TextField(max_length=500, blank=True)
    # design_tools = models.TextField(max_length=500,default="",blank=True)
    # insta_improvement = models.TextField(blank=False,null=False)
    
    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.event = Event.objects.filter(active=True).first()
        super(Registration, self).save()

    def __str__(self):
        return "{} || {} || {}".format(self.name, self.branch, str(self.year))


class Domain(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Gender(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class ContactInfo(models.Model):
    active = models.BooleanField(default=False)
    member_name = models.CharField(max_length=255)
    contact_number = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "contact_information"

    def __str__(self):
        return self.member_name


class Blog(models.Model):
    title = models.CharField(max_length=80, blank=False, null=False)
    author = models.CharField(max_length=30,blank=False,null=False)
    content = RichTextUploadingField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('blog_detail',kwargs={'pk':self.pk})


    def __str__(self):
        return "{} | {}".format(self.title, self.author)


class EmailContent(models.Model):
    event = models.ForeignKey('Event',on_delete=models.CASCADE)
    mail_allowed = models.BooleanField(default=False)
    subject = models.CharField(max_length=100)
    text = RichTextField()

    def __str__(self):
        return self.event.name


class EmailAttachment(models.Model):
    event = models.ForeignKey('Event',on_delete=models.CASCADE)
    files = models.FileField(   

Core/templates/alumni-registration.html
{% load static %}
{% load recaptcha2 %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'images/silogo.ico' %}">

    <title>Registration Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="{% static 'css/invitation.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
    <script src="sweetalert2.all.min.js"></script>
    <link rel="text/html" href="sweetalert2.min.css">
    {% recaptcha_init %}

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-sm-12 res_grid">
            <img class="svg_pic" src="{% static 'images/def.svg' %}">
        </div>
        <div class="col-md-6 col-sm-12">
   <div id="wrapper">
            <div class="form-content">
                <div class="logo_heading"><img class="si_logo" src="{% static 'images/head_silogo.svg' %}">
                <span class="form-heading">ALUMNI MEET</span></div>
                <form method="POST" id="alumni-form">
                    {% csrf_token %}
                    <div class="input-group">
                      <i class="fas fa-user" ></i>
                        <span id="name_err" class='validationerror'> </span>
                        <input  id="Name" maxlength="225" name="name"  placeholder="Enter Name" type="text" autocomplete="off">

                        <span class="bar"></span>
                    </div>

                    <div class="input-group">
                        <i class="fas fa-calendar"></i>
                        <span id="batch_err" class='validationerror'></span>
                     <input id="id_batch" maxlength="4" name="batch" type="text" autocomplete="off" placeholder="Pass out year">
                        <span class="bar"></span>
                    </div>


                    <div class="input-group">
                        <i class="fas fa-phone"></i>
                        <span id="contactno_err" class='validationerror'></span>
                        <input  id="Contact" name="contact_no" onblur="" placeholder="Enter Contact No." type="text" autocomplete="off">
                        <span class="bar"></span>
                    </div>

                    <div class="input-group">
                        <i class="fa fa-calendar-plus calndr" aria-hidden="true"></i>
                        <select class="dropdown" id="id_date" name="date">
                            <option value="" selected="selected" disabled>Preferred Date</option>
                         <option value="22 September(Sunday)">22 September(Sunday)</option>
                         <option value="29 September(Sunday)">29 September(Sunday)</option>
                         <option value="2  October(Wednesday)">2 October(Wednesday)</option>
                        </select>
                        <span style="margin:32px 0 0 0px;" id="date_err" class='validationerror'></span>
                    </div>
                    <div class="input-group">
                        <i class="fas fa-comments"></i>
                       <input id="id_message" maxlength="500" name="message" placeholder="Your best wishes" type="text" autocomplete="off">
                        <span class="bar"></span>
                    </div>
                    <div class="input-group captcha">
                   {{ form.captcha }}
                    <span  id="captcha_err" style="color: red">{{ form.captcha.errors }}</span>

                    </div>
<!--                    <div class="confirmation">-->
<!--                        Are you interested?-->
<!--                    </div>-->
                    <div class="input-group" >
                        <button  value='1' name="confirm" onclick="return validateForm()" >
                            <h2 style="margin-bottom:0rem;">Accept</h2>
                        </button>
<!--                       <button value='0'  name="confirm" onclick="return validateForm(this.value)"  >-->
<!--                        <i class="fa fa-thumbs-down fa-0.5x"></i>-->
<!--                       </button>-->
                    </div>
                </form>
            </div>
        </div>
        </div>
    </div>
</div>
</body>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/js/mdb.min.js"></script>
<script src='https://www.google.com/recaptcha/api.js'></script>
<!-- <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> -->
<script>
$(document).ready(function () {
        $("#name_err").hide();
        $("#Name").focusout(function (event) {
            if (event.charCode!=0) {
                var regex = new RegExp("^[a-zA-Z ]{2,40}$");
                if (!regex.test($(this).val())) {
                    document.getElementById('name_err').innerHTML = "Invalid Name";
                    $( "#name_err" ).show();

                }
            }
            if ( $(this).val() == "") {
                    document.getElementById('name_err').innerHTML = "Name cannot be empty";
                    $( "#name_err" ).show();

                }
         });
         $("#Name").focusin(function (event) {
            if (event.charCode!=0) {
                $( "#name_err" ).hide();
                document.getElementById('name_err').innerHTML == "";

            }
        });


             $("#Contact").focusout(function (event) {
            if (event.charCode!=0) {
                var regex = new RegExp(/^(?:(?:\+|0{0,2})91(\s*[\ -]\s*)?|[0]?)?[6789]\d{9}|(\d[ -]?){10}\d$/);
                if (!regex.test($("#Contact").val())) {
                    document.getElementById('contactno_err').innerHTML = "Invalid Contact Number";
                    $( "#contactno_err" ).show();

                }
            }
            if ( $(this).val() == "") {
                    document.getElementById('contactno_err').innerHTML = "Contact cannot be empty";
                    $( "#contactno_err" ).show();

                }
        });

        $("#Contact").attr('maxlength', 10);

        $("#Contact").focusin(function (event) {
            if (event.charCode!=0) {
                $( "#contactno_err" ).hide();
                document.getElementById('contactno_err').innerHTML == "";

            }
        });
        $("#id_batch").focusout(function (event) {
            if (event.charCode!=0) {

                var regex = new RegExp("^2009|201[0-9]$");

                if (!regex.test($("#id_batch").val())) {
                    document.getElementById('batch_err').innerHTML = "Invalid Passout Year";
                    $( "#batch_err" ).show();

                }
            }
            if ( $(this).val() == "") {
                    document.getElementById('batch_err').innerHTML = "Pass out year cannot be empty";
                    $( "#batch_err" ).show();

                }
        });
        $("#id_batch").focusin(function (event) {
            if (event.charCode!=0) {
                $( "#batch_err" ).hide();
                document.getElementById('batch_err').innerHTML == "";

            }
        });
        $("#id_date").focusout(function (event) {

            if ( $(this).val() == null) {
                    document.getElementById('date_err').innerHTML = "Choose date";
                    $( "#date_err" ).show();

                }
        });
       $("#id_date").focusin(function (event) {
            if (event.charCode!=0) {
                $( "#date_err" ).hide();
                document.getElementById('date_err').innerHTML == "";

            }
        });


        });

</script>
<script>
    function validateForm(value) {
        document.getElementById('captcha_err').innerHTML = "";
         document.getElementById('date_err').innerHTML = "";
        var name =  document.getElementById('Name').value;
        if (name == "") {
            document.getElementById('name_err').innerHTML = "Name cannot be empty"
            $( "#name_err" ).show();
            return false;
        }
        else {
        var regex = new RegExp("^[a-zA-Z ]{2,40}$");
                if (!regex.test(name)) {
                    document.getElementById('name_err').innerHTML = "Invalid Name";
                    $( "#name_err" ).show();
                    return false
                }
        }

           var batch =  document.getElementById('id_batch').value;
        if (batch == "") {
            document.getElementById('batch_err').innerHTML = "Passout year cannot be empty"
            $( "#batch_err" ).show();
            return false;
        }
        else {

                var regex = new RegExp("^2009|201[0-9]$");

                if (!regex.test(batch)) {
                    document.getElementById('name_err').innerHTML = "Invalid Passout year";
                    $( "#batch_err" ).show();
                    return false
                }
        }

        var Contact =  document.getElementById('Contact').value;
        if (Contact == "") {
            document.getElementById('contactno_err').innerHTML = "Contact cannot be empty";

            return false;
        }
        else {
            var re = /^(?:(?:\+|0{0,2})91(\s*[\ -]\s*)?|[0]?)?[6789]\d{9}|(\d[ -]?){10}\d$/;
            if(!re.test(Contact)){
                document.getElementById('contactno_err').innerHTML = "Contact number format invalid";

                return false;
            }
        }



        var date = $("#id_date");
        console.log(date.val())
        if (date.val() == null)
        { console.log("working")
          document.getElementById('date_err').innerHTML = "Choose the date";
          console.log(document.getElementById('date_err').innerHTML)
          return false;
        }
        var v = grecaptcha.getResponse();
        if(v.length == 0)
        {
            document.getElementById('captcha_err').innerHTML="Cannot be empty";
            return false;
        }


$('#alumni-form').on('submit', function(event){

    event.preventDefault();
            Swal.fire({
        title: 'Registered!',
        type: 'success',
        showCancelButton: false,
        showConfirmButton: false,
        timer:60000,

       });
       this.submit();
});
        }
</script>
</html>

Core/templates/alumni_profile.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Alumni Profile</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Catamaran&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Quicksand:400,700&display=swap" rel="stylesheet">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.7/js/mdb.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/alumni_profile.css' %}">
</head>
<body>
  <div class="container ">
  	<div class="row">
  			<div class="col-md-6 col-sm-12 ">
  				<div class="quote">
  			<h1 style="transform: scale(-1,1); text-align: center; font-size: 8rem;align-content: center; line-height: 0.5;padding: 0% 0% 0% 0%;font-family: 'Catamaran', sans-serif; ">"</h1>
			  <img class="object2" src="{% static 'images/para_shadow.svg' %}">
		<p class="quote_content" style="font-family: Montserrat,sans-serif; font-size:40px;font-weight:bold; line-height: 1.5;
		padding: 0% 0% 0% 0%;margin: 0% 0% 0% 0%;">
			{{ alumnus.message }}
		</p>

       <h1 style="text-align: center; font-size: 8rem; align-content: center;  line-height: 1.5;padding: 0% 0% 0% 0%;font-family: 'Catamaran', sans-serif;">"</h1>
 </div>
	</div>
	<div class="col-md-6 col-sm-12">
  <div class="content" id="MOT">
	<div class="box">
        <img class="object img-fluid" src="{% static 'images/pic_shadow.svg' %}">
        <div class="front_card">
			<div class="pro_img" style="background: url({{ alumnus.pic_path.url }}); background-repeat: no-repeat; background-size:cover; height: 50vh; padding:1%;">
			</div>
			<div class="hello">
				<h1 class="name">{{ alumnus.name }}</h1>
				<h1 class="domain" style="font-family: 'Nunito Sans';">{{ alumnus.batch|add:"-4" }}-{{alumnus.batch}}</h1>
				<button class="btnOpen" onclick="OpenMOT()">To know more</button>
			</div>
		</div>	
		<div class="team">
			<button class="btnClose" onclick="CloseMOT()">&times;</button>
			<div class="data-for-thumbnail">
				<div class="bg-header cp-big">
					<div class="title">
						<img class="silogo" src="{% static 'images/silogo_rename.png' %}">
						<div class="si">
						<h2 class="software">SOFTWARE</h2>
						<h2 class="incubator">INCUBATOR</h2>
						</div>
					</div>
				</div>
				<div class="strip"></div>
				<div class="about">
					<h2>Testimonial</h2>
					<p style="color:#7b7b7b;  height: 165px; 
                overflow-x: hidden; 
                overflow-x: auto; 
                text-align:justify;">{{ alumnus.testimonial }}</p>
					<i class="fas fa-envelope"></i><span style="line-height: 2; color:#7b7b7b;">{{ alumnus.email }}</span>
					<br>
					<i class="fas fa-phone"></i><span style="line-height: 2; color:#7b7b7b;">{{ alumnus.phone }}</span>
				</div>
				<div class="center">
					<div id="social-test">
					<ul class="social">
						<li><a href="{{ alumnus.facebook }}"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="{{ alumnus.linkedin }}"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
						<li><a href="{{ alumnus.github }}"><i class="fa fa-github" aria-hidden="true"></i></a></li>
					</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
</div>
</div>
</div>
</body>
<script type="text/javascript">
	
	function OpenMOT()
	{document.getElementById("MOT").classList.add("rotate-box")}

function CloseMOT()
	{document.getElementById("MOT").classList.remove("rotate-box")}

var slideIndex = 1;
    showSlides(slideIndex);
function showSlides(n){
   var i;
   var slides = document.getElementsByClassName("data-for-thumbnail");
   if(n > slides.length){slideIndex = 1}
   if(n < 1){slideIndex = slides.length}
   for(i = 0; i < slides.length; i++){
       slides[i].style.display = "none"
   }
   slides[slideIndex-1].style.display = "block"
}

var carousel = document.querySelector(".people");
var cellCount = 8;
var selectedIndex = 0;
function getCarousel(){
   var angle = selectedIndex / cellCount * -360;
   carousel.style.transform = "rotateY(" + angle + "deg)"
}

function prev(n){
   showSlides(slideIndex += n);
   selectedIndex--;
   getCarousel()
}

function next(n){
   showSlides(slideIndex += n);
   selectedIndex++;
   getCarousel()
}

</script>
</html>

Core/templates/email_template.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Silive</title>
    <link href="https://fonts.googleapis.com/css?family=Lato|Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body style="margin: 0px;">
    <div style="width: 100%;background-image: linear-gradient(180deg,#a0e2ff,#fff);">
        <div class="jumbotron" style="padding-top: 5px;padding-bottom: 20px;">
            <h4 style="font-family: 'Lato', sans-serif;margin: 0px;padding: 5px 10px;font-size: 24px;">Contact Us Registration</h4>
        </div>
        <div class="container" style="padding: 5px;">
            <div class="row">
                <div class="col-sm-4 text-md-left">
                    {% autoescape off %}
                        <ul class="list-group list-group-flush">
                            Hey Admin,<br>
                            A person has registered himself in the contact us section of <a href="http://silive.in/">silive.in</a>
                            with following details:-<br>
                            <li class="list-group-item"><b>Name</b>  -- {{ name }}</li>
                            <li class="list-group-item"><b>Email</b>  -- {{ email }}</li> 
                            <li class="list-group-item"><b>Contact Number</b>  -- {{ contact }}</li>
                            <li class="list-group-item"><b>Subject</b>  -- {{ subject }}</li>
                            <li class="list-group-item"><b>Message</b>  -- {{ message }}</li>
                        </ul>
                    {% endautoescape %}
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Core/templates/event_email_template.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Silive</title>
    <link href="https://fonts.googleapis.com/css?family=Lato|Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <style>
        span {
            background-color:#ffffff00 !important;
        }
    </style>
</head>
<body style="margin: 0px;">
    <div style="width: 100%;">
        <!-- <div style="padding-top: 5px;padding-bottom: 10px; padding-left: 5px;">
            <img src="cid:{{ event.pic_path }}" class="img-thumbnail" style="height: 60%; width: 50%;">
        </div> -->
        <div class="container" style="padding: 5px;">
            <div class="row">
                <div class="col-sm-4 text-md-left">
                    {% autoescape off %}
                    {{ content.text|safe }}
                    {% endautoescape %}
                </div>
            </div>
        </div><br>
        <div class="container" style="padding: 5 px;text-align: center">
            <img height="80px" src="http://i.imgur.com/5SQX270.png" alt="silogo">
            <p style="color: #000">Powered by <a href="http://silive.in/">Software Incubator</a></p>
            <h4 style="color: #000">Love.Peace.Code !!</h4>
        </div>
    </div>
</body>
</html>